### ISSUE TITLE
No matches for kind ADOTCollector when following AWS guide.

### ISSUE THREAD

**Issue by boarder7395** [aws-observability/aws-otel-community#103]
I am following the below guide for launching AWS ADOT collector for Xray.
https://docs.aws.amazon.com/eks/latest/userguide/configure-cw.html

When launching the resource the following error occurs:
error: unable to recognize "collector-config-xray.yaml": no matches for kind "ADOTCollector" in version "opentelemetry.io/v1alpha1"

I expect the issue is related to the recent change on this line from
kind: OpenTelemetryCollector to kind: ADOTCollector

https://github.com/aws-observability/aws-otel-community/blob/bde1b8cf5aa45ea702cd5d0614b2112adfe1fd34/sample-configs/operator/collector-config-xray.yaml#L2

**Comment by bryan-aguilar** [comment]
Thank you for the report. This was indeed a mistake, a PR has been submitted to fix this.
