### ISSUE TITLE
Namespace for k8s metrics

### ISSUE THREAD

**Issue by crigertg** [aws-observability/aws-otel-community#161]
# Current behaviour

When collecting k8s metrics with `awscontainerinsightreceiver`  and exporting using `awsemf` the namespace is always set to the configured value in the metrics. 

# Desired behaviour

The metrics regarding pods/services/replicasets etc should contain the k8s Namespace the resources are running in. 

It seems that there is no possibility to configure this behaviour. Or am I missing something?

**Comment by vsakaram** [comment]
@crigertg can you please clarify if this is same as https://github.com/aws-observability/aws-otel-collector/issues/1712 ?

**Comment by crigertg** [comment]
@vsakaram yes this is the same issue. When opening this I wasn't aware of the cause. Sorry for not updating this issue. I'll close it.
