### ISSUE TITLE
What's the significance of this being in "preview"?

### ISSUE THREAD

**Issue by jmm** [aws-observability/aws-otel-community#18]
https://aws.amazon.com/otel describes it as both "preview" and "production-ready". If it's production-ready, then what makes it a preview? Is it lack of comprehensive feature set?

For features / contexts it supports, is there anything that makes it unsuitable for production use?

**Comment by alolita** [comment]
Public preview for ADOT implies upstream OpenTelemetry components are not declared stable yet (they may be available as release candidates or beta or alpha versions upstream). Typically, we keep ADOT components in public preview until the OTEL upstream community guarantees stability for data signals (e.g. traces, metrics) or for specific components (e.g. Java SDK 1.0 for traces).
