### ISSUE TITLE
Could not locate AppDynamics Exporter

### ISSUE THREAD

**Issue by MacNale** [aws-observability/aws-otel-community#20]
Team,

I was looking to export traces and metrics to AppDynamics. I could not locate any exporter. The partner ecosystem was mentioned on the https://aws.amazon.com/blogs/aws/public-preview-aws-distro-open-telemetry/ blog.

Just wondering if there is any support for AppDynamics?

thanks,
Mac

**Comment by alolita** [comment]
Hi @MacNale AppDynamics is still working on their OpenTelemetry components so not available in ADOT yet.
