### ISSUE TITLE
Correction to ADOT Documentation Partners (Datadog) Section 

### ISSUE THREAD

**Issue by alyspapp** [aws-observability/aws-otel-community#22]
Within the ADOT documentation (https://aws-otel.github.io/docs/partners/datadog) under Partners, the left side navigation reads "DataDog". The second d in Datadog should not be capitalized. Please update this to read "Datadog".
![OTel documentation_Datadog section_screenshot](https://user-images.githubusercontent.com/68347436/108429964-a8152a00-720e-11eb-96d2-9b996cdfffa5.png)

**Comment by alolita** [comment]
@alyspapp please file this request on https://github.com/aws-otel/aws-otel.github.io/issues Thanks!

**Comment by anuraaga** [comment]
Thanks @alyspapp - sent https://github.com/aws-otel/aws-otel.github.io/pull/82 to fix

**Comment by alolita** [comment]
Thanks for the fix @anuraaga

**Comment by alyspapp** [comment]
Thank you!
