### ISSUE TITLE
AWS DISTRO Otel collector exporter AWS MSK (Kafka)

### ISSUE THREAD

**Issue by jhonatanforero** [aws-observability/aws-otel-community#27]
Hi, 
Do you have AWS MSK (Kafka) exporter enable with AWS Distro?
I mean if  is it possible send traces from Distro Otel collector to MSK (Kafka)?

**Comment by alolita** [comment]
@jhonatanforero We do not have AWS MSK support enabled in ADOT but will assess what needs to be done to add this support. Stay tuned.
