### ISSUE TITLE
https://aws-otel.github.io/ copyright need to be updated to 2023 year. 

### ISSUE THREAD

**Issue by aiziumov** [aws-observability/aws-otel-community#298]
Hi! As of today copyright at the bottom of the page is: "© 2020–2021 Amazon Web Services" - makes sense to update to "© 2020–2023 Amazon Web Services".

**Comment by PaurushGarg** [comment]
Closing this issue as the relevant PR has been merged: https://github.com/aws-otel/aws-otel.github.io/pull/569
