### ISSUE TITLE
Elasticsearch/Open Distro as backend

### ISSUE THREAD

**Issue by raghu999** [aws-observability/aws-otel-community#3]
Is it possible to use opendistro elastic as a backend?

**Comment by alolita** [comment]
Hi @raghu999 thanks for opening up our first community question. 

Open Distro support with an exporter is in the works. Keep a lookout on our roadmap at https://github.com/orgs/aws-observability/projects/4

You may have already found the upstream exporter at https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/master/exporter/elasticexporter
