### ISSUE TITLE
Global propagators documentation (Python) out of date

### ISSUE THREAD

**Issue by smcoll** [aws-observability/aws-otel-community#30]
**Describe the bug**
Python documentation at https://aws-otel.github.io/docs/getting-started/python-sdk/trace-auto-instr#setting-the-global-propagators says to define progagators this way:

```
from opentelemetry import propagators
from opentelemetry.sdk.extension.aws.trace.propagation.aws_xray_format import AwsXRayFormat

propagators.set_global_textmap(AwsXRayFormat())
```
But as of `opentelemetry-api==1.3.0` (and likely earlier), that method has been moved:

```
AttributeError: module 'opentelemetry.propagators' has no attribute 'set_global_textmap'
```

This appears to do the trick:
```
from opentelemetry import propagate
from opentelemetry.sdk.extension.aws.trace.propagation.aws_xray_format import AwsXRayFormat

propagate.set_global_textmap(AwsXRayFormat())
```

**Comment by NathanielRN** [comment]
This was actually recently updated to be the following:

```python
from opentelemetry import propagate
from opentelemetry.propagators.aws import AwsXRayPropagator

propagate.set_global_textmap(AwsXRayPropagator())
```

in the [trace-manual-instr](https://github.com/aws-otel/aws-otel.github.io/blob/main/src/docs/getting-started/python-sdk/trace-manual-instr.mdx#sending-traces-to-aws-x-ray) page.

So this was closed in https://github.com/aws-otel/aws-otel.github.io/pull/188 . Closing the issue.
