### ISSUE TITLE
Hi, Is it possible to send traces to only X-Ray and not other resources like CloudWatch? Thank you!

### ISSUE THREAD

**Issue by greeshma-r** [aws-observability/aws-otel-community#36]

**Comment by anuraaga** [comment]
Hi @greeshma-r - you will generally use the OpenTelemetry collector along with an application. The collector is configured with a yaml file, setting where any data is exported. Unless you configure this to export to Cloudwatch, it won't (nor will it send to X-Ray either unless configured to do so).

**Comment by greeshma-r** [comment]
Thank you @anuraaga :)
