### ISSUE TITLE
About adjusting the frequency of fetching sampling rules when using X-Ray remote sampling.

### ISSUE THREAD

**Issue by sakeafterbeer** [aws-observability/aws-otel-community#395]
I have a question regarding using X-Ray Remote Sampling with OTEL_TRACES_SAMPLER=xray. When I edit a sampling rule from the AWS X-Ray Console, it takes about 3 minutes for the rule to take effect. Is it possible to adjust how often the sampling rule is updated?

**Comment by wangzlei** [comment]
The remote sampling is service specific feature, the default X-Ray sampling rule retrieve [interval is 5 minutes](https://github.com/open-telemetry/opentelemetry-java-contrib/blob/425128399ecb52c05ab2afd0de774b529933c691/aws-xray/src/main/java/io/opentelemetry/contrib/awsxray/AwsXrayRemoteSamplerBuilder.java#L22). User can customize it by AwsXrayRemoteSamplerBuilder but it is not recommended, the small interval means more GetSamplingRules requests, you can adjust it during testing but for a stable prod environment, the interval 5 minutes is ok.

**Comment by sakeafterbeer** [comment]
Thank you for your response. I will use the default interval. If I want an immediate update, I will restart the container.

**Comment by srprash** [comment]
@sakeafterbeer I assume you are using the aws remote sampler in OTel Java.
I believe the sampler should be fetching the rules out-of-band if the sampling rules were updated before the next periodic fetch is due. 
This is being done in the remote sampler in Go [here](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/8538a773eb81e44260cb04118ae3002d18abfe32/samplers/aws/xray/remote_sampler.go#L154-L158). 
Maybe this is a missing feature in the Java one. Doing a [quick search](https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-java-contrib%20LastRuleModification&type=code) for `LastRuleModification` in the java implementation didn't provide a result of the expected logic.

**Comment by sakeafterbeer** [comment]
@srprash Yes, I am using aws remote sampler. 
I think Golang's behavior is good. But so far, the default interval seems to work fine. Thanks for your information.
