### ISSUE TITLE
Update GitHub Actions which utilize NodeJS.12

### ISSUE THREAD

**Issue by humivo** [aws-observability/aws-otel-community#435]
https://github.blog/changelog/2023-05-04-github-actions-all-actions-will-run-on-node16-instead-of-node12/

https://github.com/aws-observability/aws-otel-community/actions/workflows/integration-test.yml

**Comment by PaurushGarg** [comment]
Closing issue as the relevant PR has been merged.

**Comment by vsakaram** [comment]
PR Reference: https://github.com/aws-observability/aws-otel-community/pull/447
