### ISSUE TITLE
errors in master/sample-configs/operator/collector-config-amp.yaml

### ISSUE THREAD

**Issue by pgasca** [aws-observability/aws-otel-community#450]
**Describe the bug**
The current version of master/sample-configs/operator/collector-config-amp.yaml specifies apiVersion: opentelemetry.io/v1alpha1 and kind: OpenTelemetryCollector. When you run this you get "error: unable to recognize "collector-config-amp.yaml": no matches for kind "OpenTelemetryCollector" in version "opentelemetry.io/v1alpha1"". Need to fix with the correct values.

**Steps to reproduce**
https://docs.aws.amazon.com/en_us/eks/latest/userguide/deploy-deployment.html

**What did you expect to see?**
Install open telemetry collector for prometheus

**What did you see instead?**
error: unable to recognize "collector-config-amp.yaml": no matches for kind "OpenTelemetryCollector" in version "opentelemetry.io/v1alpha1"

**Environment**
Describe any aspect of your environment relevant to the problem.

**Additional context**
This was contributed by external feedback. Please follow up using the email address from this SIM if any more information is needed:
https://issues.amazon.com/issues/AWSDocsSchedule-27453

**Comment by bryan-aguilar** [comment]
The EKS Add-on must first be installed by following the instructions [here](https://docs.aws.amazon.com/en_us/eks/latest/userguide/opentelemetry.html).

**Comment by pgasca** [comment]
Added prereqs to various ADOT sections to emphasize that requirement.
