### ISSUE TITLE
Dynatrace exporter config docs mention invalid key

### ISSUE THREAD

**Issue by arminru** [aws-observability/aws-otel-community#55]
The docs in https://aws-otel.github.io/docs/partners/dynatrace still list the config key `insecure_skip_verify` at top-level although this config was restructured in the collector a while ago (see the [collector readme](https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/configtls/README.md)) and nested into a section `tls`.
This is the same issue as reported here: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7566
The [exporter readme](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/dynatraceexporter/README.md) in the collector was fixed in https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/6cfac22ceefca654d1445cab499b1be2b79b9096 and https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/c8dc4b921250d5d164eceae00d2c339291615a16.
Could you please take over these changes in https://aws-otel.github.io/docs/partners/dynatrace or instruct us how to update the docs there?
Thanks!

**Comment by alolita** [comment]
Hi @arminru can you please file this issue and a PR to fix the docs on the ADOT tech docs site at https://github.com/aws-otel/aws-otel.github.io/ 

Here is the guide to make changes and file a PR at https://github.com/aws-otel/aws-otel.github.io/blob/main/DEV_GUIDE.md

**Comment by arminru** [comment]
Will do, thanks for the pointer @alolita! I missed that repository as it's located in a different Github org.
