### ISSUE TITLE
Potential documentation issue on aws-otel.github.io site

### ISSUE THREAD

**Issue by marcinbelczewski** [aws-observability/aws-otel-community#56]
Hello

I believe there might be a documentation issue in this section of the aws-otel site: [Collecting infrastructure metrics](https://aws-otel.github.io/docs/getting-started/container-insights#collecting-infrastructure-metrics)

The section says: *ADOT Collector uses the [AWS Container Insights Receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/awscontainerinsightreceiver)* and the link leads to **awscontainerinsightreceiver** GitHub folder however, below in a list of supported platforms, the following bullet - *[Amazon ECS with cluster- and service-level metrics](https://aws-otel.github.io/docs/components/ecs-metrics-receiver)*, leads to a site section describing the usage of a completely different receiver - **awsecscontainermetrics**.

Is that intentional or a documentation problem? Can **awscontainerinsightreceiver** actually be used with AWS ECS to collect cluster and service level metrics (e.g. for Fargate)?

Cheers,
Marcin

**Comment by alolita** [comment]
Hi @marcinbelczewski thanks for flagging! We'll take a look and fix.

**Comment by alolita** [comment]
Hi @marcinbelczewski can you please file an issue on the ADOT docs site at https://github.com/aws-otel/aws-otel.github.io/issues Thanks!

**Comment by marcinbelczewski** [comment]
Hi @alolita, thank you for replying. I have just created the issue as suggested: https://github.com/aws-otel/aws-otel.github.io/issues/252

Cheers,
Marcin

**Comment by bryan-aguilar** [comment]
We are tracking this in the website repo.
