### ISSUE TITLE
Go sample app: Support for configurable otlp endpoint

### ISSUE THREAD

**Issue by bonclay7** [aws-observability/aws-otel-community#585]
Feature request to provide a metric or trace exporter via environment variable or config file. By default `localhost:4317` is used, and would be nice to override that value, using https://pkg.go.dev/go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc#WithEndpoint

**Comment by Aneurysm9** [comment]
Does the existing [environment variable-based configuration](https://github.com/open-telemetry/opentelemetry-go/tree/main/exporters/otlp/otlptrace#configuration) from the Go SDK's OTLP trace exporter not already do this?  This should be the case for each language.  In any event, if we were to add such configuration it would first need to be introduced to [the specification](https://github.com/aws-observability/aws-otel-community/blob/master/sample-apps/SampleAppSpec.md#configuration) and then implemented in each sample application.

**Comment by bonclay7** [comment]
Thanks for the infos. I wasn’t able to make it work with the existing environment-variables based configurations, but maybe I’m missing something. Is the SDK supposed to override the default values of the env vars are provided?

**Comment by bonclay7** [comment]
I confirm, Go SDK variables work fine, was a misconfiguration on my side, thanks
