### ISSUE TITLE
.NET framework versions issues

### ISSUE THREAD

**Issue by EvgeniyGolovashev** [aws-observability/aws-otel-community#597]
My Application work with Framework 4.5.2
I tried to send to the ADOT receiver and export them to the X-Ray on the ADOT exporter

https://aws-otel.github.io/docs/getting-started/dotnet-sdk/trace-manual-instr#requirements
The AWS Distro for OpenTelemetry .NET SDK is compatible for .NET framework (net452 and above) and .NET Core (netstandard2.0 and above).
https://www.nuget.org/packages/OpenTelemetry.Contrib.Instrumentation.AWS
NET Framework 4.5.2

But OpenTelemetry minimum stable version for  .NET Framework 4.6.2

**Comment by vasireddy99** [comment]
Thank you so much for bringing this to our attention, we are currently working to update our docs.
