### ISSUE TITLE
Support for JavaScript auto-instrumentation

### ISSUE THREAD

**Issue by pawelkaliniakit** [aws-observability/aws-otel-community#658]
Currently, ADOT supports manual instrumentation in the [JavaScript SDK ](https://aws-otel.github.io/docs/getting-started/javascript-sdk). It would be desirable to provide support for [auto-instrumentation](https://opentelemetry.io/docs/instrumentation/js/automatic/).

**Comment by vsakaram** [comment]
This is being tracked as part of https://github.com/aws-otel/aws-otel.github.io/issues/260, hence closing this to avoid duplication.
