### ISSUE TITLE
cert-manager version for ADOT add-on

### ISSUE THREAD

**Issue by edgo19** [aws-observability/aws-otel-community#75]
Hello,
There is a note on the ADOT add-on requirements page https://aws-otel.github.io/docs/getting-started/adot-eks-add-on/requirements#tls-certificate-requirement saying that cert-manager with version < 1.6 is required. It prevents to use the latest version for other components, e.g. integrating appmesh mutual TLS with cert-manager. This version is old and there are CVEs ASAIK
Why is this limitation?
ADOT add-on fails in installation if cert-manager is not installed if I want to use another method to create certificates for webhooks

Thanks

**Comment by mhausenblas** [comment]
@edgo19 hello, ADOT PM here! Thanks for brining this up, will look into it.

**Comment by erichsueh3** [comment]
Documentation has been updated - we recommend the latest cert-manager version now

**Comment by edgo19** [comment]
Thanks!
