### ISSUE TITLE
Tracing with the AWS Distro for OpenTelemetry Python SDK and X-Ray documentation incorrect

### ISSUE THREAD

**Issue by hkford** [aws-observability/aws-otel-community#81]
**Describe the bug**
[Tracing with ADOT Python SDK and X-Ray documentation](https://aws-otel.github.io/docs/getting-started/python-sdk/trace-manual-instr) uses some old classes.

**What did you expect to see?**
[Sending Traces to AWS X-Ray](https://aws-otel.github.io/docs/getting-started/python-sdk/trace-manual-instr#sending-traces-to-aws-x-ray) should be like the following because `BatchExportSpanProcessor` is renamed to `BatchSpanProcessor` at [this PR](https://github.com/open-telemetry/opentelemetry-python/pull/1656) and `AwsXRayIdsGenerator` is renamed to `AwsXRayIdGenerator` at [this PR](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/350).
```
from opentelemetry.sdk.trace.export import BatchSpanProcessor
from opentelemetry.sdk.extension.aws.trace import AwsXRayIdGenerator
# Sends generated traces in the OTLP format to an ADOT Collector running on port 4317
otlp_exporter = OTLPSpanExporter(endpoint="http://localhost:4317")
# Processes traces in batches as opposed to immediately one after the other
span_processor = BatchSpanProcessor(otlp_exporter)
```

**What did you see instead?**
At [Sending Traces to AWS X-Ray](https://aws-otel.github.io/docs/getting-started/python-sdk/trace-manual-instr#sending-traces-to-aws-x-ray), doc says: 
```
from opentelemetry.sdk.trace.export import BatchExportSpanProcessor
from opentelemetry.sdk.extension.aws.trace import AwsXRayIdsGenerator
# Sends generated traces in the OTLP format to an ADOT Collector running on port 4317
otlp_exporter = OTLPSpanExporter(endpoint="http://localhost:4317")
# Processes traces in batches as opposed to immediately one after the other
span_processor = BatchExportSpanProcessor(otlp_exporter)
```

**Comment by bryan-aguilar** [comment]
Hi thank you for the contribution! Looks like the documentation is out of date. As a note, we do accept contributions to the [website repo](https://github.com/aws-otel/aws-otel.github.io) if you were interested in filing a PR.

**Comment by hkford** [comment]
Raised [a PR](https://github.com/aws-otel/aws-otel.github.io/pull/374)
